runtime: php74
runtime_config:
    document_root: .

handlers:
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
  
- url: /
  static_files: pages/login/login.php
  upload: pages/login/login.php