runtime: php74
runtime_config:
    document_root: .

handlers:
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
  
- url: /assets/(.*\.(gif|png|jpg|ico))
  static_files: assets/\1
  upload: assets/(.*\.(gif|png|jpg|ico))