application: codex-bu
runtime: php74
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/index.php
  upload: website/index.php

- url: /
  static_dir: website

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico