runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /(.+\.php)$
  script: \1

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|svg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg|ico)$
  application_readable: true

- url: /.*
  script: index.php


