runtime: php74

handlers:
- url: /(.+\.php)$
  script: \1
- url: /.*
  script: index.php
- url: /assets
  static_dir: assets
- url: /pages
  static_dir: pages
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$