runtime: php74

handlers:

- url: /.*
  script: index.php
  
- url: /
  static_files: pages/login/login.php
  upload: pages/login/login.php

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico