runtime: php55
api_version: 1
threadsafe: true

handlers:
# Allow multi-pages
- url: /(.+\.php)$
  script: \1

# Upload images
- url: /(.+\.(gif|png|jpg|svg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg|ico)$
  application_readable: true

# Upload CSS files
- url: /css/(.*\.(css|scss))$
  static_files: css/\1
  upload: css/.*\.(css|scss)$

# Upload JavaScript files
- url: /js/(.*\.(js))$
  static_files: js/\1
  upload: css/.*\.(js)$

# Landing Page
- url: /.*
  script: index.php
  secure: always
  redirect_http_response_code: 301


