runtime: php74
runtime_config:
    document_root: .

handlers:
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /assets/(.*\.(gif|png|jpg))
  static_files: assets/\1
  upload: assets/(.*\.(gif|png|jpg))