runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /(.+\.php)$
  script: \1

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /assets/favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /.*
  script: index.php


