runtime: php74
runtime_config:
    document_root: .

handlers:
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
  
- url: /assets
  static_dir: assets
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico