runtime: php74
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /assets
  static_dir: assets
- url: /css
  static_dir: css
- url: /js
  static_dir: js
