runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/index.html
  upload: website/index.html

- url: /
  static_dir: website

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
